name: Release

on:
  push:
    branches:
      - github-action
    tags:
      - 'v*.*.*'
      - 'rc-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build TPS-Bench
        run: |
          cd tps-bench && cargo build --release
          cd target/release
          tar -czvf tps-bench_${GITHUB_REF##*/}_x86_64-unknown-linux-gnu.tar.gz  tps-bench
      - name: Release TPS-Bench
        uses: softprops/action-gh-release@v1
        with:
          files: "target/release/tps-bench_${GITHUB_REF##*/}_x86_64-unknown-linux-gnu.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
