name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'rc-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
      - name: Build TPS-Bench
        run: |
          cd tps-bench && cargo build --release
          cd target/release
          tar -czf ${{ github.workspace }}/tps-bench_${{ env.GIT_TAG_NAME }}_x86_64-unknown-linux-gnu.tar.gz  tps-bench
      - name: Release TPS-Bench
        uses: softprops/action-gh-release@v1
        with:
          files: "tps-bench_${{ env.GIT_TAG_NAME }}_x86_64-unknown-linux-gnu.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
